WIP: (Do not merge) Edge signatures
emeraldpay/dshackle pull request #160
Opened 2022-05-14 15:31 UTC by Termina1

Functions to sign dshackle responses when returned via gRPC.
Signs only if response has not already been signed.

[ ] Fix all tests
[ ] Figure out how to handle signatures if error occurs (think we should sign errors too)
[ ] Add tests for signatures feature
[ ] Clean up
[ ] Make PR to Java API repository

2022-05-16 15:32 UTC, Termina1 commented
Waiting https://github.com/emeraldpay/emerald-grpc/pull/4 to be merged and propagated to Java API library

2022-05-23 01:50 UTC, splix requested changes

2022-05-23 13:58 UTC, Termina1 commented on src/main/kotlin/io/emeraldpay/dshackle/config/SignatureConfig.kt
> +    var signScheme: String = "SHA256withDSA"
I made a enum with different sign scheme, but with another values

2022-05-23 13:58 UTC, Termina1 commented on src/main/kotlin/io/emeraldpay/dshackle/config/SignatureConfig.kt
> +    var algorithm: String = "DSA"
Made another enum for algoright, may be we would like to add some post quantum crypto as well =)

2022-05-24 14:35 UTC, Termina1 commented on src/main/kotlin/io/emeraldpay/dshackle/config/SignatureConfig.kt
> +    var signScheme: String = "SHA256withDSA"
Updated: removed signing schemes from config, now only sha256 is available

2022-05-24 14:36 UTC, Termina1 commented on src/main/kotlin/io/emeraldpay/dshackle/rpc/CurrentResponseSigner.kt
> +    override fun sign(message: ByteArray): String {
Now I directly pass nonce and message inside this method

2022-05-27 03:00 UTC, merged